global:
route:
  receiver: 'hugot'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [alertname]
receivers:
- name: hugot
  webhook_configs:
    - url: http://localhost:PORT/hugot/prometheus/alerts
